export const Data = [
    {
      bannerId: 1401,
      imageUrl: "https://plentyspkimages.s3.amazonaws.com/Banner/Carousel/mobileHome/1676458515344main_banner_3_mob.jpg",
      imagePath: "",
      priority: 4,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 12,
      pageLocation: "mobileHome",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 31,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/GC-Banner-v2.png",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 18,
      pageLocation: "mobileGiftCard",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 35,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileHome/kidtoys.png",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 19,
      pageLocation: "mobileBestProduct",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 36,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileBestProduct/Best-Products-3rd.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 19,
      pageLocation: "mobileBestProduct",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 37,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileComingSoon/Coming-soon-1st.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 20,
      pageLocation: "mobileComingSoon",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 38,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileComingSoon/Coming-soon-3rd.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 20,
      pageLocation: "mobileComingSoon",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 39,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileComingSoon/Coming-soon-4th.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 20,
      pageLocation: "mobileComingSoon",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 40,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileFreshBazar/Fifth.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 21,
      pageLocation: "mobileFreshBazar",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 41,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileFreshBazar/Fourth.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 21,
      pageLocation: "mobileFreshBazar",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 42,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileFreshBazar/Second.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 21,
      pageLocation: "mobileFreshBazar",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 47,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileFreshBazar/Sixth.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 21,
      pageLocation: "mobileFreshBazar",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 48,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileFreshBazar/Third.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 21,
      pageLocation: "mobileFreshBazar",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 49,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Carousel/mobileFreshBazar/First-v2.jpg",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 21,
      pageLocation: "mobileFreshBazar",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 92,
      imageUrl: "https://plentyspkimages.s3.ap-south-1.amazonaws.com/Banner/Images/policy/privacypolicy_v5.png",
      imagePath: "",
      priority: 5,
      mobileScreen: "",
      mobile: 1,
      mobileScreenProps: "",
      lookupBannerPageId: 26,
      pageLocation: "/policy",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 1006,
      imageUrl: "https://plentyspkimages.s3.amazonaws.com/Banner/Images/mobileCheckout/1634895101707express_delivery_no_text_01_v2.png",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 31,
      pageLocation: "mobileCheckout",
      lookupBannerType: 1,
      bannerType: "Image",
      startTime: null,
      endTime: null
    },
    {
      bannerId: 1020,
      imageUrl: "https://plentyspkimages.s3.amazonaws.com/Banner/Carousel/mobileTodayDeal/ 1635848983900promotions-mobile_new_nov21.png",
      imagePath: "",
      priority: 5,
      mobileScreen: null,
      mobile: 1,
      mobileScreenProps: null,
      lookupBannerPageId: 13,
      pageLocation: "mobileTodayDeal",
      lookupBannerType: 2,
      bannerType: "Carousels",
      startTime: null,
      endTime: null
    }
  ]